name: "Google Drive Upload Action"
description: "Uploads files to Google Drive with options to preserve folder structure, process multiple input branches, and skip files."
author: "Your Name"
inputs:
  input:
    description: "Paths to one or more folders to be uploaded. Separate multiple paths by a space."
    required: true
  filter:
    description: "Glob pattern to filter files in the input folders."
    required: false
    default: "*"
  output:
    description: "Path to the folder on Google Drive where the files should be uploaded."
    required: true
  target:
    description: "Folder ID of the Drive root folder."
    required: true
  credentials:
    description: "Base64 encoded credentials.json or a path to the credentials file."
    required: true
  purgeStale:
    description: "Set to 'true' to delete stale files in the output folder."
    required: false
    default: "false"
  flatUpload:
    description: "Set to 'true' to flatten the directory structure and upload all files into the same folder."
    required: false
    default: "false"
  skip:
    description: "Comma-separated glob patterns of files to skip (e.g., '*.tmp,*.log')."
    required: false
    default: ""
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      shell: bash
      run: |
        python3 -m venv "${GITHUB_ACTION_PATH}/.venv"
        source "${GITHUB_ACTION_PATH}/.venv/bin/activate"
        python3 -m pip install --no-cache-dir google-auth google-auth-httplib2 google-auth-oauthlib google-api-python-client"
    - name: Perform upload
      id: upload-files-to-google-drive
      shell: bash
      run: |
        source "${GITHUB_ACTION_PATH}/.venv/bin/activate"
        python3 "${GITHUB_ACTION_PATH}/main.py" \
          --input "${{ inputs.input }}" \
          --filter "${{ inputs.filter }}" \
          --output "${{ inputs.output }}" \
          --target "${{ inputs.target }}" \
          --credentials "${{ inputs.credentials }}" \
          --purge-stale="${{ inputs.purgeStale }}" \
          --flat-upload="${{ inputs.flatUpload }}" \
          --skip="${{ inputs.skip }}"
